"""
Pydantic v2 data models for the repository index.

These models are the shared data contract between all indexer modules.
Everything is JSON-serialisable via ``model.model_dump_json()``.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class Language(str, Enum):
    """Programming language detected in a source file."""

    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    JAVA = "java"
    GO = "go"
    CPP = "cpp"
    UNKNOWN = "unknown"


class SymbolKind(str, Enum):
    """The kind of a code symbol extracted from a source file."""

    FUNCTION = "function"
    CLASS = "class"
    METHOD = "method"
    IMPORT = "import"
    EXPORT = "export"
    INTERFACE = "interface"


# ---------------------------------------------------------------------------
# Fine-grained symbol
# ---------------------------------------------------------------------------


class Symbol(BaseModel):
    """A single named entity (function, class, import …) found in a file."""

    name: str = Field(description="Symbol name as it appears in source code.")
    kind: SymbolKind
    line_start: int = Field(description="1-based line number where the symbol starts.")
    line_end: int = Field(description="1-based line number where the symbol ends.")
    parent: str | None = Field(
        default=None,
        description="Name of the enclosing class/function (set for methods).",
    )


# ---------------------------------------------------------------------------
# Per-file summary
# ---------------------------------------------------------------------------


class FileSummary(BaseModel):
    """
    Semantic summary for a single source file.

    Generated by the summarizer from AST symbols + raw text; no LLM call.
    """

    path: str = Field(description="Path relative to the repository root.")
    language: Language
    purpose: str = Field(
        description="One-sentence description of the file's role, "
        "derived from its docstring or first comment."
    )
    major_classes: list[str] = Field(
        default_factory=list,
        description="Top class names in this file.",
    )
    important_functions: list[str] = Field(
        default_factory=list,
        description="Notable (non-private) function/method names.",
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="Module/package names this file imports.",
    )
    symbols: list[Symbol] = Field(
        default_factory=list,
        description="All symbols extracted from this file.",
    )
    loc: int = Field(default=0, description="Lines of code (non-blank, non-comment).")
    total_lines: int = Field(default=0, description="Total lines including blanks/comments.")


# ---------------------------------------------------------------------------
# Dependency graph edge
# ---------------------------------------------------------------------------


class DependencyEdge(BaseModel):
    """A directed dependency between two files (or a file and an external module)."""

    source_file: str = Field(description="Relative path of the importing file.")
    target: str = Field(
        description="Relative path of the imported file, or the external module name."
    )
    kind: str = Field(
        default="import",
        description="Edge kind: 'import', 'export', 'inherit', 'implement'.",
    )


# ---------------------------------------------------------------------------
# Repository-wide statistics
# ---------------------------------------------------------------------------


class RepositoryStatistics(BaseModel):
    """Aggregate statistics computed over the whole repository."""

    total_files: int = 0
    total_loc: int = Field(default=0, description="Sum of LOC across all files.")
    total_lines: int = Field(default=0, description="Sum of total lines across all files.")
    language_breakdown: dict[str, int] = Field(
        default_factory=dict,
        description="Files per language, e.g. {'python': 12, 'javascript': 4}.",
    )
    language_loc: dict[str, int] = Field(
        default_factory=dict,
        description="LOC per language.",
    )
    total_functions: int = 0
    total_classes: int = 0
    total_imports: int = 0
    most_connected_files: list[str] = Field(
        default_factory=list,
        description="Files with the most import edges (in + out degree), top-10.",
    )
    top_level_packages: list[str] = Field(
        default_factory=list,
        description="Top-level directory names that look like packages.",
    )
    dependency_graph_nodes: int = 0
    dependency_graph_edges: int = 0


# ---------------------------------------------------------------------------
# Top-level index
# ---------------------------------------------------------------------------


class RepositoryIndex(BaseModel):
    """
    The complete index for a repository.

    Returned by ``CodebaseAnalyzer.analyze_repository()`` and persisted as JSON.
    """

    repo_path: str = Field(description="Absolute path to the analysed repository.")
    repo_name: str = Field(description="Basename of the repository root directory.")
    file_tree: list[str] = Field(
        default_factory=list,
        description="Sorted list of relative file paths.",
    )
    summaries: dict[str, FileSummary] = Field(
        default_factory=dict,
        description="Per-file summary keyed by relative path.",
    )
    dependency_graph: list[DependencyEdge] = Field(
        default_factory=list,
        description="All detected import/export dependency edges.",
    )
    statistics: RepositoryStatistics = Field(
        default_factory=RepositoryStatistics,
    )
    # Raw adjacency list kept for quick lookups without rebuilding the graph
    adjacency: dict[str, list[str]] = Field(
        default_factory=dict,
        description="adjacency[file] = list of files/modules it depends on.",
    )
